name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests-pyshark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y tshark
          mkdir -p "$HOME/Desktop"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
          pip install -r requirements.txt
      - name: Lint
        run: flake8 src/ tests/
      - name: Test
        run: pytest -q

  tests-no-pyshark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y tshark
          mkdir -p "$HOME/Desktop"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
          pip install -r requirements.txt
      - name: Remove pyshark
        run: pip uninstall -y pyshark || true
      - name: Lint
        run: flake8 src/ tests/
      - name: Test
        run: pytest -q

  docs:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
          pip install -r requirements.txt
      - name: Build docs
        run: make -C docs html
      - name: Upload docs artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs-html
          path: docs/_build
